# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/ #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期データをマウントする場所
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: dbclass_server # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=root #コンテナ内のMySQLを起動する際のパスワードを設定
